In [16]:
# Importar Librerías y paquetes de Python para análisis de datos
#import requests
#import pandas as pd
#import json
#import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns

# Importación de librerías esenciales para el análisis de datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [19]:
# Estilo de gráficos
sns.set(style="whitegrid", palette="pastel")

#📌 Extracción

In [20]:
# Cargar datos desde la URL
url = 'https://raw.githubusercontent.com/alura-cursos/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'
df = pd.read_json(url)
df

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [21]:
df.shape  # Tamaño de Filas y columnas

(7267, 6)

In [22]:
df.info()  # Información de columnas y tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

#🔧 Transformación

In [23]:
# Expandimos el DataFrame desanidando columnas
df_expandido = pd.concat([
    df.drop(['customer', 'phone', 'internet', 'account'], axis=1), # Eliminamos columnas anidadas
    pd.json_normalize(df['customer']),  # Normalizamos datos de cliente
    pd.json_normalize(df['phone']),     # Normalizamos datos de teléfono
    pd.json_normalize(df['internet']),  # Normalizamos datos de internet
    pd.json_normalize(df['account'])    # Normalizamos datos de cuenta
], axis=1)
# Mostramos las primeras filas del nuevo DataFrame
df_normalizado = df_expandido

In [24]:
df_expandido.sample(10) #Mostrando el df aleatoriamente

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
5955,8138-EALND,No,Male,0,No,No,15,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.75,311.6
2069,2911-UREFD,Yes,Female,0,Yes,No,39,No,No phone service,DSL,...,No,Yes,No,Yes,Yes,Month-to-month,No,Electronic check,55.90,2184.35
5424,7416-CKTEP,No,Female,0,Yes,No,57,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.60,1134.25
5987,8183-ONMXC,Yes,Female,0,No,No,2,Yes,No,Fiber optic,...,No,No,No,No,Yes,Month-to-month,No,Electronic check,80.75,159.45
2623,3656-TKRVZ,Yes,Female,0,No,No,3,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,No,Electronic check,55.35,165.2
5262,7176-WRTNX,No,Male,0,No,No,70,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),114.95,7711.25
810,1143-NMNQJ,Yes,Female,0,No,No,2,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.70,169.8
4729,6479-VDGRK,No,Female,0,Yes,Yes,72,Yes,No,DSL,...,Yes,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),85.30,6129.2
7142,9824-QCJPK,No,Male,0,Yes,No,36,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.00,666.75
2504,3498-LZGQZ,No,Male,0,Yes,Yes,63,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,19.15,1177.05

In [25]:
df_expandido.info()  # Información de columnas y tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [26]:
# ¿Hay datos nulos?
df_expandido.isna().sum()

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64

In [27]:
#¿Existen duplicados?
duplicados = df[df['customerID'].duplicated(keep=False)]
duplicados

Empty DataFrame
Columns: [customerID, Churn, customer, phone, internet, account]
Index: []

In [28]:
# Cambiamos el tipo de variable y el nombre a "Charges.Monthly" y "Charges.Total"
df_expandido['Charges.Monthly'] = pd.to_numeric(df_expandido['Charges.Monthly'], errors='coerce')
df_expandido['Charges.Total'] = pd.to_numeric(df_expandido['Charges.Total'], errors='coerce')

df_expandido.rename(columns={'Charges.Monthly': 'Charges_Monthly'}, inplace=True)
df_expandido.rename(columns={'Charges.Total': 'Charges_Total'}, inplace=True)

In [29]:
df_expandido.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges_Monthly,Charges_Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40

In [30]:
# Renombraremos ciertas columnas
df_expandido.rename(columns={
    'customerID': 'Customer_ID',
    'gender': 'Gender',
    'tenure': 'Tenure'
}, inplace=True)

In [ ]:
df_expandido.tail() #Mostramos las últimas 5 filas

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges_Monthly,Charges_Total
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

In [32]:
# Creamos nueva Columna y dividiendo cada valor entre 30
df_expandido['daily_accounts'] = df_expandido['Charges_Monthly'] / 30

In [33]:
df_expandido.sample(5)

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges_Monthly,Charges_Total,daily_accounts
952,1342-JPNKI,Yes,Male,0,No,No,10,Yes,Yes,Fiber optic,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),86.05,834.10,2.868333
3944,5385-SUIRI,Yes,Male,1,Yes,No,52,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,104.20,5568.35,3.473333
471,0670-ANMUU,No,Male,0,No,No,71,Yes,Yes,Fiber optic,...,No,Yes,No,Yes,One year,No,Credit card (automatic),97.65,6687.85,3.255000
4201,5766-ZJYBB,Yes,Male,0,No,No,1,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.40,19.40,0.646667
976,1371-OJCEK,No,Female,0,No,No,48,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),24.35,1133.70,0.811667

In [34]:
# Columnas a transformar en binario - Solo columnas puras "Yes"/"No".
binary_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']

# Aplicamos la transformación a binario
df_expandido[binary_cols] = df_expandido[binary_cols].apply(lambda x: x.map({'Yes': 1, 'No': 0}))

df_expandido.sample(5)

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges_Monthly,Charges_Total,daily_accounts
6567,9031-ZVQPT,No,Male,0,1,0,72,1,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Two year,1,Electronic check,108.20,7840.60,3.606667
2342,3259-QMXUN,No,Male,0,1,0,58,1,Yes,DSL,...,Yes,No,Yes,Yes,Two year,1,Electronic check,86.10,4890.50,2.870000
3827,5235-XATIX,,Male,0,0,1,22,1,No,Fiber optic,...,Yes,No,Yes,No,Month-to-month,1,Electronic check,89.40,2001.50,2.980000
3224,4501-VCPFK,No,Male,0,0,0,26,0,No phone service,DSL,...,Yes,Yes,No,No,Month-to-month,0,Electronic check,35.75,1022.50,1.191667
6657,9146-JRIOX,No,Female,0,1,1,14,1,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,0,Mailed check,25.55,372.45,0.851667

In [35]:
# Reemplazar "No phone service" por "No" en MultipleLines.
df_expandido['MultipleLines'] = df_expandido['MultipleLines'].replace('No phone service', 'No')
df_expandido['MultipleLines'].value_counts()

MultipleLines
No     4202
Yes    3065
Name: count, dtype: int64

In [36]:
# Convertir "Yes"/"No" a 1/0 en MultipleLines.
df_expandido['MultipleLines'] = df_expandido['MultipleLines'].map({'Yes': 1, 'No': 0})
df_expandido['MultipleLines'].head()

0    0
1    1
2    0
3    0
4    0
Name: MultipleLines, dtype: int64

In [37]:
df_expandido.Contract.value_counts()

Contract
Month-to-month    4005
Two year          1743
One year          1519
Name: count, dtype: int64

In [38]:
# Reemplazar valores en Contract según criterios definidos.
contract_mapping = {
    'Month-to-month': 1,
    'One year': 2,
    'Two year': 3
}

df_contract = pd.DataFrame(list(contract_mapping.items()), columns=['Contract Type', 'Code'])
print(df_contract)

    Contract Type  Code
0  Month-to-month     1
1        One year     2
2        Two year     3

In [39]:
# Columnas donde "Sí" será 1 y el resto 0.
binary_cols_2 = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in binary_cols_2:
    df_expandido[col] = df_expandido[col].apply(lambda x: 1 if x == 'Yes' else 0)

df_expandido

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges_Monthly,Charges_Total,daily_accounts
0,0002-ORFBO,No,Female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,0,0,13,1,0,DSL,...,0,1,0,0,One year,0,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,0,1,0,22,1,1,Fiber optic,...,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,0,0,0,2,1,0,DSL,...,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,1,1,67,1,0,DSL,...,1,1,0,1,Two year,0,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,1,1,63,0,0,DSL,...,1,0,1,1,Two year,0,Electronic check,59.00,3707.60,1.966667

In [40]:
# Recorremos la columna 'Churn'.
# Si el valor es 'Yes' o 'No', lo conservamos tal cual.
# Para cualquier otro valor, lo reemplazamos por 'N/A'.
df_expandido['Churn'] = df_expandido['Churn'].apply(lambda x: x if x == 'Yes' or x =='No' else 'N/A')
df_expandido

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges_Monthly,Charges_Total,daily_accounts
0,0002-ORFBO,No,Female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,0,0,13,1,0,DSL,...,0,1,0,0,One year,0,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,0,1,0,22,1,1,Fiber optic,...,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,0,0,0,2,1,0,DSL,...,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,1,1,67,1,0,DSL,...,1,1,0,1,Two year,0,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,1,1,63,0,0,DSL,...,1,0,1,1,Two year,0,Electronic check,59.00,3707.60,1.966667

In [41]:
df_expandido['Churn'].value_counts() #conteo de valores

Churn
No     5174
Yes    1869
N/A     224
Name: count, dtype: int64

In [42]:
df_final = df_expandido

In [43]:
df_final.to_json('Churn_de_Clientes.json', index= False)

#📊 Carga y análisis

#📄Informe final