In [8]:
# Importación de librerías esenciales para el análisis de datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import warnings
#warnings.filterwarnings('ignore')

print("Librerías cargadas exitosamente.")

Librerías cargadas exitosamente.

In [9]:
# Estilo de gráficos
sns.set_theme(context='notebook', style='whitegrid', palette='muted')

#📌 Extracción

In [10]:
# Cargar datos desde la URL
url = 'https://raw.githubusercontent.com/alura-cursos/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'
df = pd.read_json(url)
df

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [13]:
# Información de columnas y tipos de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

#🔧 Transformación

In [35]:
# Expandimos el DataFrame normalizando las columnas
df_normalizado = pd.concat([
    df.drop(['customer', 'phone', 'internet', 'account'], axis=1), # Eliminamos las columnas anidadas
    pd.json_normalize(df['customer']),  # Normalizamos datos de cliente
    pd.json_normalize(df['phone']),     # Normalizamos datos de teléfono
    pd.json_normalize(df['internet']),  # Normalizamos datos de internet
    pd.json_normalize(df['account'])    # Normalizamos datos de cuenta
], axis=1)

# Mostramos las primeras filas del nuevo DataFrame
df_normalizado.sample()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
4359,5981-ZVXOT,No,Female,1,No,No,35,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Yes,One year,Yes,Electronic check,108.35,3726.15

In [36]:
# Mostrando el DataFrame aleatoriamente
df_normalizado.sample(10)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
3915,5353-WILCI,No,Female,0,No,No,28,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,No,Electronic check,56.05,1522.65
238,0361-HJRDX,No,Female,0,No,No,68,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),64.35,4539.6
1760,2504-DSHIH,No,Male,1,Yes,No,23,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,No,Electronic check,86.80,1975.85
1403,2027-CWDNU,No,Male,0,Yes,Yes,18,Yes,No,Fiber optic,...,No,No,Yes,No,Yes,Month-to-month,Yes,Electronic check,85.60,1601.5
2414,3373-DIUUN,No,Male,0,Yes,Yes,30,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,21.25,711.9
5292,7233-PAHHL,No,Male,0,Yes,Yes,66,Yes,Yes,DSL,...,No,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,84.00,5714.25
5018,6861-OKBCE,Yes,Female,0,No,Yes,11,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),20.10,221.35
6308,8676-TRMJS,Yes,Male,0,No,No,3,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,No,Mailed check,75.00,209.1
548,0781-LKXBR,Yes,Male,1,No,No,9,Yes,Yes,Fiber optic,...,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.50,918.6
4036,5522-JBWMO,No,Male,0,No,Yes,1,Yes,No,DSL,...,No,No,No,No,No,Month-to-month,No,Electronic check,44.00,44

In [37]:
# Información de columnas y tipos de datos
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [38]:
# Verificación de datos nulos
df_normalizado.isna().sum()

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64

In [39]:
# Cambiamos el nombre  de "Charges.Monthly" y "Charges.Total"
df_normalizado.rename(columns={
    'Charges.Monthly': 'ChargesMonthly',
    'Charges.Total': 'ChargesTotal'
}, inplace=True)

# Cambiamos el tipo de variable de "ChargesMonthly" y "ChargesTotal"
df_normalizado['ChargesMonthly'] = pd.to_numeric(df_normalizado['ChargesMonthly'], errors='coerce')
df_normalizado['ChargesTotal'] = pd.to_numeric(df_normalizado['ChargesTotal'], errors='coerce')

In [41]:
df_normalizado.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40

In [42]:
# Renombramos las columnas de customer ID, gender y tenure
df_normalizado.rename(columns={
    'customerID': 'Customer_ID',
    'gender': 'Gender',
    'tenure': 'Tenure'
}, inplace=True)

In [47]:
# Mostramos las últimas 5 filas
df_normalizado.tail()

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

In [51]:
# Creamos nueva Columna y dividiendo cada valor entre 30
df_normalizado['daily_accounts'] = df_normalizado['ChargesMonthly'] / 30

In [53]:
# Verificamos una muestra
df_normalizado.sample(5)

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal,daily_accounts
6876,9489-DEDVP,No,Female,0,Yes,Yes,70,Yes,Yes,DSL,...,No,No,Yes,No,Two year,Yes,Credit card (automatic),69.20,4872.35,2.306667
5785,7905-TVXTA,No,Female,0,No,No,5,Yes,No,DSL,...,No,Yes,Yes,No,Month-to-month,Yes,Electronic check,64.35,352.65,2.145000
541,0771-CHWSK,No,Male,0,No,No,66,Yes,Yes,DSL,...,Yes,No,No,Yes,Two year,Yes,Credit card (automatic),74.60,4798.40,2.486667
1637,2324-AALNO,No,Female,0,No,No,48,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),24.55,1203.95,0.818333
2427,3392-EHMNK,No,Female,0,Yes,Yes,67,Yes,Yes,Fiber optic,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),94.10,6302.80,3.136667

In [54]:
# Columnas a transformar en binario - Solo columnas puras "Yes"/"No".
binary_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']

# Aplicamos la transformación a binario
df_normalizado[binary_cols] = df_normalizado[binary_cols].apply(lambda x: x.map({'Yes': 1, 'No': 0}))

df_normalizado.sample(5)

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal,daily_accounts
6344,8728-SKJLR,No,Male,0,0,0,41,1,No,Fiber optic,...,No,Yes,No,No,Month-to-month,1,Electronic check,74.25,3089.10,2.475000
4517,6194-HBGQN,No,Male,0,0,0,51,1,Yes,DSL,...,Yes,Yes,Yes,No,One year,1,Credit card (automatic),81.15,4126.20,2.705000
3735,5144-PQCDZ,No,Male,0,0,0,4,1,No,No,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,1,Mailed check,19.95,59.25,0.665000
5903,8065-BVEPF,No,Male,1,0,0,65,1,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,1,Bank transfer (automatic),99.10,6496.15,3.303333
6359,8741-LQOBK,No,Female,0,1,1,46,0,No phone service,DSL,...,No,No,No,No,Month-to-month,0,Bank transfer (automatic),35.05,1620.25,1.168333

In [56]:
# Reemplazar el valor "No phone service" por "No" en MultipleLines.
df_normalizado['MultipleLines'] = df_normalizado['MultipleLines'].replace('No phone service', 'No')
df_normalizado['MultipleLines'].value_counts()

MultipleLines
No     4202
Yes    3065
Name: count, dtype: int64

In [57]:
# Convertir los valores "Yes"/"No" a 1/0 en MultipleLines.
df_normalizado['MultipleLines'] = df_normalizado['MultipleLines'].map({'Yes': 1, 'No': 0})
df_normalizado['MultipleLines'].head()

0    0
1    1
2    0
3    0
4    0
Name: MultipleLines, dtype: int64

In [58]:
df_normalizado.Contract.value_counts()

Contract
Month-to-month    4005
Two year          1743
One year          1519
Name: count, dtype: int64

In [61]:
# Reemplazar valores en Contract según criterios definidos.
contract_mapping = {
    'Month-to-month': 1,
    'One year': 2,
    'Two year': 3
}

df_contract = pd.DataFrame(list(contract_mapping.items()), columns=['Contract Type', 'Code'])
print(df_contract)

    Contract Type  Code
0  Month-to-month     1
1        One year     2
2        Two year     3

In [62]:
# Columnas donde el valor es "Sí" será 1 y el resto 0.
binary_cols_2 = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

for col in binary_cols_2:
    df_normalizado[col] = df_normalizado[col].apply(lambda x: 1 if x == 'Yes' else 0)

df_normalizado

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal,daily_accounts
0,0002-ORFBO,No,Female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,0,0,13,1,0,DSL,...,0,1,0,0,One year,0,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,0,1,0,22,1,1,Fiber optic,...,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,0,0,0,2,1,0,DSL,...,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,1,1,67,1,0,DSL,...,1,1,0,1,Two year,0,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,1,1,63,0,0,DSL,...,1,0,1,1,Two year,0,Electronic check,59.00,3707.60,1.966667

In [63]:
# Recorremos la columna 'Churn'.
# Si el valor es 'Yes' o 'No', lo conservamos tal cual.
# Para cualquier otro valor, lo reemplazamos por 'N/A'.
df_normalizado['Churn'] = df_normalizado['Churn'].apply(lambda x: x if x == 'Yes' or x =='No' else 'N/A')
df_normalizado

,Customer_ID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal,daily_accounts
0,0002-ORFBO,No,Female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,0,0,13,1,0,DSL,...,0,1,0,0,One year,0,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,0,1,0,22,1,1,Fiber optic,...,0,0,0,1,Month-to-month,1,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,0,0,0,2,1,0,DSL,...,0,0,0,0,Month-to-month,1,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,0,1,1,67,1,0,DSL,...,1,1,0,1,Two year,0,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,0,1,1,63,0,0,DSL,...,1,0,1,1,Two year,0,Electronic check,59.00,3707.60,1.966667

In [64]:
# Conteo de valores
df_normalizado['Churn'].value_counts()

Churn
No     5174
Yes    1869
N/A     224
Name: count, dtype: int64

In [66]:
# Creamos un DataFrame final a partir del DataFrame normalizado
df_final = df_normalizado.copy()

In [67]:
# Exportamos el DataFrame final en formato .json
df_final.to_json('Churn_de_Clientes.json', index= False)

#📊 Carga y análisis

#📄Informe final